pool:
  vmImage: 'Ubuntu-16.04'
  demands: 
          -npm
  
  steps:
  - task: DotNetCoreInstall@0
    displayName: 'Use .NET Core SDK 2.2.301'
    inputs: 
        version: 2.2.301'

  - task: Npm@1
    displayName: 'Run npm install'
    inputs:
        verbose: false

  - script: './node_modules/.bin/node-sass Tailspin.SpaceGame.Web/wwwroot --output Tailspin.SpaceGame.Web/wwwroot'
    displayName: 'Compile Sass assets'

  - task: gulp@1
    displayName: "Run gulp tasks"

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > builinfo.txt'
    displayName: 'Write Build Info'
    workingDirectory: Tailspin.SpaceGame.Web/wwwroot

  - task: DotNetCoreCL@2
    displayName: 'Restore project dependencies'
    inputs:
        command: 'restore'
        projects: '**/*.csproj'

  - task: DotNetCoreCL@2
    displayName: 'Build the project - Release'
    inputs:
        command: 'build'
        arguments: '--no-restore --configuration Release'
        projects: '**/*.csproj'

